version: '3'
services:
  web:
    build: .
    #image: ccasado/postmortem:v1
    command: python manage.py makemigrations
    command: python manage.py migrate --noinput
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DBAAS_MYSQL_HOST: db
      DBAAS_MYSQL_DATABASE: docker
      DBAAS_MYSQL_USER: root
      DBAAS_MYSQL_PASSWORD: docker
      OAUTH2_ENDPOINT: ""
      OAUTH2_CLIENT_ID: ""
      OAUTH2_CLIENT_SECRET: ""
      MYSQL_ROOT_PASSWORD: docker
    
    depends_on:
      - db
    links:
      - db
  db:
    #https://hub.docker.com/_/mysql/
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker

    ports:
      - 3306:3306
    
