# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='', max_length=100, verbose_name='Item')),
                ('action_type', models.CharField(choices=[('MIT', 'mitiga\xe7\xe3o'), ('PREV', 'preven\xe7\xe3o'), ('PROC', 'processo'), ('OTH', 'outro')], default='other', max_length=50, verbose_name='Type')),
                ('owner', models.CharField(default='', max_length=50, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('product', models.CharField(default='', max_length=50, verbose_name='Product')),
                ('authors', models.CharField(default='', max_length=100, verbose_name='Authors')),
                ('summary', models.CharField(default='', max_length=100, verbose_name='Summary')),
                ('impact', models.TextField(default='', help_text='Efeito sobre o usu\xe1rio final ou ao neg\xf3cio.', verbose_name='Impact')),
                ('root_causes', models.TextField(default='', help_text='Explica\xe7\xe3o sobre as circunst\xe2ncias em que o incidente ocorreu. Pode ser \xfatil usar a t\xe9cnica 5 Whys.', verbose_name='Root causes')),
                ('trigger', models.CharField(blank=True, default='', max_length=100, verbose_name='Trigger')),
                ('resolution', models.TextField(default='', verbose_name='Resolution')),
                ('detection', models.CharField(blank=True, default='', max_length=100, verbose_name='Detection')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='report',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Report'),
        ),
    ]
