# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('summary', models.TextField(verbose_name='Summary')),
            ],
        ),
    ]
