# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('TODO', 'TODO'), ('Conclu\xeddo', 'Conclu\xeddo')], default='TODO', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('Mitiga\xe7\xe3o', 'mitiga\xe7\xe3o'), ('Preven\xe7\xe3o', 'preven\xe7\xe3o'), ('Processo', 'processo'), ('Outro', 'outro')], default='other', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='product',
            field=models.CharField(default='', max_length=50, verbose_name='Produto'),
        ),
    ]
