# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='detection',
            field=models.TextField(default='SOME STRING', verbose_name='Detection'),
        ),
        migrations.AddField(
            model_name='report',
            name='impact',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='resolution',
            field=models.TextField(default='SOME STRING', verbose_name='Resolution'),
        ),
        migrations.AddField(
            model_name='report',
            name='root_causes',
            field=models.TextField(default='SOME STRING', verbose_name='Root causes'),
        ),
        migrations.AddField(
            model_name='report',
            name='trigger',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
