# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180228_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='impact',
            field=models.CharField(default='SOME STRING', max_length=50, verbose_name='Impact'),
        ),
    ]
