# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180228_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='trigger',
            field=models.CharField(default='SOME STRING', max_length=50, verbose_name='Trigger'),
        ),
    ]
