# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180228_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='detection',
            field=models.CharField(default='SOME STRING', max_length=100, verbose_name='Detection'),
        ),
        migrations.AlterField(
            model_name='report',
            name='impact',
            field=models.CharField(default='SOME STRING', max_length=100, verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='report',
            name='summary',
            field=models.CharField(default='SOME STRING', max_length=100, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='report',
            name='trigger',
            field=models.CharField(default='SOME STRING', max_length=100, verbose_name='Trigger'),
        ),
    ]
