# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180228_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='SOME STRING', max_length=100, verbose_name='Item')),
                ('action_type', models.CharField(choices=[('MIT', 'mitigate'), ('PREV', 'prevent'), ('PROC', 'process'), ('OTH', 'other')], default='other', max_length=50, verbose_name='Type')),
            ],
        ),
    ]
