# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='report',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Report'),
        ),
    ]
