# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180304_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='impact',
            field=models.TextField(default='', verbose_name='Impact'),
        ),
    ]
